"""Tests for InterProScan scientific acceptance assertions (Phase E)."""

from __future__ import annotations

import json
from pathlib import Path

from tools.run_interproscan_real_checks import (
    EXPECTED_C14,
    EXPECTED_SM_IMPORTED_ORIGINS,
    EXPECTED_SM_MISSING_TRANSLATIONS,
)


def test_expected_acceptance_constants():
    """Verify expected acceptance constants for C14 and SM."""
    assert len(EXPECTED_C14["output_sha256"]) == 64
    assert EXPECTED_C14["insertions"] == 34080
    assert EXPECTED_C14["candidate_count"] == 37942
    assert EXPECTED_C14["emitted_candidate_count"] == 34079
    assert len(EXPECTED_SM_MISSING_TRANSLATIONS) == 5
    assert len(EXPECTED_SM_IMPORTED_ORIGINS) == 6


def test_interproscan_acceptance_report_if_present():
    """If acceptance report was generated by real checks, verify all gates passed."""
    report_path = Path(".test-output/interproscan-gates/interproscan-real-checks.json")
    if not report_path.is_file():
        return
    report = json.loads(report_path.read_text(encoding="utf-8"))
    assert len(report) == 4
    for row in report:
        assert row["status"] == "passed", (
            f"Check {row['label']} failed: {row.get('error')}"
        )
